services:
  - type: web
    name: flownest-frontend
    env: static
    buildCommand: ./build.sh
    publishPath: Frontend/dist
    routes:
      - source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_BASE_URL
        value: https://flownest-backend.onrender.com
